patches

diff --git a/chef/cookbooks/provisioner/templates/suse/crowbar_register.erb b/chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
--- a/chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
+++ b/chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
@@ -147,6 +147,77 @@ if test "x$MD5_ADMIN" != "x$MD5_LOCAL"; then
 fi
 
 
+# Helper functions
+# ----------------
+
+get_nodes_allow_fail() {
+  # --fail is important here as we rely on the failure to know if we can
+  # communicate with the admin server
+  local curlargs=(--connect-timeout 60 -s --fail \
+                  -L
+                  -H "Accept: application/json" \
+                  --max-time 240)
+
+  [[ $CROWBAR_KEY ]] && curlargs+=(-u "$CROWBAR_KEY" --digest --anyauth)
+
+  curl "${curlargs[@]}" "http://$ADMIN_IP:3000/crowbar/machines/1.0/"
+}
+
+get_node_allow_fail() {
+  # --fail is important here as we rely on the failure for 404
+  local curlargs=(--connect-timeout 60 -s --fail \
+                  -L
+                  -H "Accept: application/json" \
+                  --max-time 240)
+
+  [[ $CROWBAR_KEY ]] && curlargs+=(-u "$CROWBAR_KEY" --digest --anyauth)
+
+  curl "${curlargs[@]}" "http://$ADMIN_IP:3000/crowbar/machines/1.0/$HOSTNAME"
+}
+
+post_allocate() {
+  local curlargs=(--connect-timeout 60 -s \
+                  -L -X POST --data-binary "{ \"name\": \"$1\" }" \
+                  -H "Accept: application/json" -H "Content-Type: application/json" \
+                  --max-time 240)
+
+  [[ $CROWBAR_KEY ]] && curlargs+=(-u "$CROWBAR_KEY" --digest --anyauth)
+
+  curl "${curlargs[@]}" "http://$ADMIN_IP:3000/crowbar/machines/1.0/allocate/0"
+}
+
+post_state() {
+  local curlargs=(-o "/var/log/crowbar/$1-$2.json" --connect-timeout 60 -s \
+                  -L -X POST --data-binary "{ \"name\": \"$1\", \"state\": \"$2\" }" \
+                  -H "Accept: application/json" -H "Content-Type: application/json" \
+                  --max-time 240)
+
+  [[ $CROWBAR_KEY ]] && curlargs+=(-u "$CROWBAR_KEY" --digest --anyauth)
+
+  curl "${curlargs[@]}" "http://$ADMIN_IP:3000/crowbar/crowbar/1.0/transition/default"
+}
+
+
+# Check that we can really register this node
+# -------------------------------------------
+
+nodes=$(get_nodes_allow_fail || echo "")
+if test -z "$nodes"; then
+  echo "Failed to contact the administration server."
+  echo "Is the administration server up?"
+  exit 1
+fi
+
+# Copied from sledgehammer
+MAC=$(cat /sys/class/net/$BOOTDEV/address)
+HOSTNAME="d${MAC//:/-}.${DOMAIN}"
+
+if get_node_allow_fail > /dev/null; then
+  echo "This node seems to be already registered."
+  exit 1
+fi
+
+
 # Setup the repos
 # ---------------
 
@@ -196,6 +267,12 @@ zypper --non-interactive install --auto-agree-with-licenses suse-sle12-cloud-com
 <% end -%>
 zypper --non-interactive install $PACKAGES_INSTALL
 
+# Fail early if we know we can't succeed because of a missing chef-client
+if ! which chef-client &> /dev/null; then
+  echo "chef-client is not available."
+  exit 1
+fi
+
 
 # Some initial setup
 # ------------------
@@ -230,37 +307,9 @@ else
 fi
 
 
-# Helper functions
-# ----------------
-
-post_allocate() {
-  local curlargs=(--connect-timeout 60 -s \
-                  -L -X POST --data-binary "{ \"name\": \"$1\" }" \
-                  -H "Accept: application/json" -H "Content-Type: application/json" \
-                  --max-time 240)
-
-  [[ $CROWBAR_KEY ]] && curlargs+=(-u "$CROWBAR_KEY" --digest --anyauth)
-
-  curl "${curlargs[@]}" "http://$ADMIN_IP:3000/crowbar/machines/1.0/allocate/0"
-}
-
-post_state() {
-  local curlargs=(-o "/var/log/crowbar/$1-$2.json" --connect-timeout 60 -s \
-                  -L -X POST --data-binary "{ \"name\": \"$1\", \"state\": \"$2\" }" \
-                  -H "Accept: application/json" -H "Content-Type: application/json" \
-                  --max-time 240)
-
-  [[ $CROWBAR_KEY ]] && curlargs+=(-u "$CROWBAR_KEY" --digest --anyauth)
-
-  curl "${curlargs[@]}" "http://$ADMIN_IP:3000/crowbar/crowbar/1.0/transition/default"
-}
-
-
 # Steps from sledgehammer
 # -----------------------
 
-MAC=$(cat /sys/class/net/$BOOTDEV/address)
-HOSTNAME="d${MAC//:/-}.${DOMAIN}"
 sed -i -e "s/\(127\.0\.0\.1.*\)/127.0.0.1 $HOSTNAME ${HOSTNAME%%.*} localhost.localdomain localhost/" /etc/hosts
 echo "$HOSTNAME" > /etc/HOSTNAME
 hostname "$HOSTNAME"
